modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Sheep-Armor/issues"

[[mods]]
modId = "sheeparmor"
version = "26.1.2.0"
displayName = "SheepArmor"
updateJSONURL = "https://updates.blamejared.com/get?n=sheeparmor&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sheep-armor"
logoFile = "logo_sheeparmor.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Grants sheep a small armor bonus while they still have wool."

[[mixins]]
config = "sheeparmor.common.mixins.json"

[[mixins]]
config = "sheeparmor.neoforge.mixins.json"

[[dependencies.sheeparmor]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.sheeparmor]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

